# Use root/example as user/password credentials
version: '3.1'

services:
  myapp:
    image: cradaca39/globant-challenge:0.0.1
    ports:
      - "5000:5000"
    depends_on:
      - mysql_db
      
  mysql_db:
    image: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xxxx
      MYSQL_DATABASE: xxx
      MYSQL_USER: xxxxx
      MYSQL_PASSWORD: xxxxx
    ports:
      - "3600:3306"
    # (this is just an example, not intended to be a production configuration)